### ISSUE TITLE
Pass the tissues, we all got issues

### ISSUE THREAD

**Issue by boblauer** [boblauer/GitHubPlus#3]
ISSUE!!!

**Comment by boblauer** [comment]
#3 test

**Comment by truonglv-eva** [comment]
If you can see this, you do not have GitHub+ installed.  To install the extension, please (email this person/visit this url/wish really really hard)
`gh+``{"updatedBy":"","updatedOn":"8/30/2016","ghplus-due-date":"08/30/2016","ghplus-estimated-hours":"5"}``gh+`

**Comment by truonglv-eva** [comment]
If you can see this, you do not have GitHub+ installed.  To install the extension, please (email this person/visit this url/wish really really hard)
`gh+``{"updatedBy":"","updatedOn":"8/30/2016","ghplus-due-date":"08/30/2016","ghplus-estimated-hours":"5"}``gh+`
